#pragma once

#include <string>

namespace minikv::shard_route_preview_operator_value_supply_signed_approval_capture_artifact_preflight_gates {

int planned_signed_approval_capture_artifact_preflight_gate_count();
std::string format_signed_approval_capture_artifact_preflight_gates_json(int published_stage_count);

} // namespace minikv::shard_route_preview_operator_value_supply_signed_approval_capture_artifact_preflight_gates
