#pragma once

#include <string>

namespace minikv::shard_route_preview_operator_value_supply_signed_approval_capture_artifact_draft_text_package_review_preflight {

std::string format_signed_approval_capture_artifact_draft_text_package_review_preflight_json();
std::string format_signed_approval_capture_artifact_draft_text_package_review_preflight_stage_catalog_json();
std::string signed_approval_capture_artifact_draft_text_package_review_preflight_digest_marker();
int published_stage_count();

} // namespace minikv::shard_route_preview_operator_value_supply_signed_approval_capture_artifact_draft_text_package_review_preflight