#pragma once

#include <string>

namespace minikv::shard_route_preview_operator_value_supply_signed_approval_capture_artifact_draft_authoring_readiness_requirements {

std::string format_signed_approval_capture_artifact_draft_authoring_readiness_requirements_json(int published_stage_count);
int planned_signed_approval_capture_artifact_draft_authoring_readiness_requirement_count();

} // namespace minikv::shard_route_preview_operator_value_supply_signed_approval_capture_artifact_draft_authoring_readiness_requirements
