#pragma once

#include "minikv/shard_route_preview_stage_catalog.hpp"

#include <span>

namespace minikv::shard_preview_release_window_readiness_packet_split_non_participation_stages {

std::span<const shard_route_preview_stage_catalog::StageRecord>
release_window_readiness_packet_split_non_participation_stages();
int first_release_window_readiness_packet_split_non_participation_release_number();
int planned_release_window_readiness_packet_split_non_participation_stage_count();

} // namespace minikv::shard_preview_release_window_readiness_packet_split_non_participation_stages
