#pragma once

#include "minikv/shard_route_preview_stage_catalog.hpp"

#include <span>

namespace minikv::shard_preview_signed_approval_artifact_draft_profile_section_integrity_stages {

std::span<const shard_route_preview_stage_catalog::StageRecord>
signed_approval_artifact_draft_profile_section_integrity_stages();
int first_signed_approval_artifact_draft_profile_section_integrity_release_number();
int planned_signed_approval_artifact_draft_profile_section_integrity_stage_count();

} // namespace minikv::shard_preview_signed_approval_artifact_draft_profile_section_integrity_stages
