#include "minikv/command_catalog.hpp"

namespace minikv::command_catalog {
namespace {

using Verb = CommandDispatchVerb;

const std::vector<CommandCatalogEntry>& catalog_entries() {
    static const std::vector<CommandCatalogEntry> catalog = {
        {"PING", "PING [message]", "meta", false, false, true,
         "Liveness check with optional echo message", Verb::Ping, false},
        {"SET", "SET key value", "write", true, true, true, "Set or update a key value", Verb::Set, true},
        {"SETNXEX", "SETNXEX key seconds value", "write", true, true, true,
         "Claim a key with value and TTL only when absent", Verb::SetNxEx, true},
        {"GET", "GET key", "read", false, false, true, "Read a key value", Verb::Get, true},
        {"DEL", "DEL key", "write", true, true, true, "Delete a key", Verb::Del, true},
        {"EXPIRE", "EXPIRE key seconds", "write", true, true, true, "Set a positive TTL on an existing key",
         Verb::Expire, true},
        {"TTL", "TTL key", "read", false, false, true, "Read a key TTL state", Verb::Ttl, true},
        {"SIZE", "SIZE", "read", false, false, true, "Return the live key count", Verb::Size, false},
        {"KEYS", "KEYS [prefix]", "read", false, false, true, "List live keys, optionally filtered by prefix",
         Verb::Keys, false},
        {"KEYSJSON", "KEYSJSON [prefix]", "read", false, false, true,
         "List live keys as JSON, optionally filtered by prefix", Verb::KeysJson, false},
        {"SAVE", "SAVE path", "admin", false, false, true, "Save a snapshot file", Verb::Save, false},
        {"LOAD", "LOAD path", "admin", true, false, true, "Load a snapshot file into the store", Verb::Load,
         false},
        {"COMPACT", "COMPACT", "admin", false, true, true, "Compact the write-ahead log", Verb::Compact,
         false},
        {"WALINFO", "WALINFO", "read", false, true, true, "Read write-ahead log maintenance details",
         Verb::WalInfo, false},
        {"STATS", "STATS", "meta", false, true, true, "Read command and connection metrics as text",
         Verb::RuntimeEvidence, false},
        {"STATSJSON", "STATSJSON", "meta", false, true, true, "Read command and connection metrics as JSON",
         Verb::RuntimeEvidence, false},
        {"SMOKEJSON", "SMOKEJSON", "meta", false, true, true, "Read combined runtime smoke evidence as JSON",
         Verb::RuntimeEvidence, false},
        {"RESETSTATS", "RESETSTATS", "admin", false, false, true, "Reset command metrics", Verb::ResetStats,
         false},
        {"HEALTH", "HEALTH", "meta", false, true, true, "Read liveness and maintenance health",
         Verb::RuntimeEvidence, false},
        {"INFO", "INFO", "meta", false, false, true, "Read server identity metadata as text",
         Verb::RuntimeEvidence, false},
        {"INFOJSON", "INFOJSON", "meta", false, false, true, "Read server identity metadata as JSON",
         Verb::RuntimeEvidence, false},
        {"SHARDJSON", "SHARDJSON", "read", false, false, true,
         "Read shard readiness evidence as JSON without enabling shard writes", Verb::RuntimeEvidence, false},
        {"SHARDROUTE", "SHARDROUTE key", "read", false, false, true,
         "Preview a key slot and shard without enabling active routing", Verb::RuntimeEvidence, false},
        {"SHARDROUTEJSON", "SHARDROUTEJSON key", "read", false, false, true,
         "Preview a key slot and shard as JSON without enabling active routing", Verb::RuntimeEvidence, false},
        {"SHARDROUTEVERIFYJSON", "SHARDROUTEVERIFYJSON key", "read", false, false, true,
         "Verify a route preview JSON contract without enabling active routing", Verb::RuntimeEvidence, false},
        {"SHARDROUTEVERIFYREPORTJSON", "SHARDROUTEVERIFYREPORTJSON key", "read", false, false, true,
         "Package route preview verification evidence without enabling active routing", Verb::RuntimeEvidence, false},
        {"SHARDROUTEVERIFYREPORTCLOSEOUTJSON", "SHARDROUTEVERIFYREPORTCLOSEOUTJSON", "read", false, false,
         true, "Read route preview verification report closeout summary without enabling active routing",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVERIFYREPORTARCHIVEJSON", "SHARDROUTEVERIFYREPORTARCHIVEJSON", "read", false, false, true,
         "Read route preview verification report archive manifest without enabling active routing",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVERIFYREPORTARCHIVECLOSEOUTJSON", "SHARDROUTEVERIFYREPORTARCHIVECLOSEOUTJSON", "read",
         false, false, true,
         "Read route preview verification report archive closeout evidence without enabling active routing",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVERIFYREPORTARCHIVECLOSEOUTVERIFYJSON", "SHARDROUTEVERIFYREPORTARCHIVECLOSEOUTVERIFYJSON",
         "read", false, false, true,
         "Read route preview verification report archive closeout verification evidence without enabling active routing",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVERIFYREPORTARCHIVECLOSEOUTVERIFYAUDITJSON",
         "SHARDROUTEVERIFYREPORTARCHIVECLOSEOUTVERIFYAUDITJSON", "read", false, false, true,
         "Read route preview verification report archive closeout verification audit evidence without enabling active routing",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVERIFYREPORTARCHIVECLOSEOUTVERIFYAUDITCLOSEOUTJSON",
         "SHARDROUTEVERIFYREPORTARCHIVECLOSEOUTVERIFYAUDITCLOSEOUTJSON", "read", false, false, true,
         "Read route preview verification report archive closeout verification audit closeout evidence without enabling active routing",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVERIFYREPORTARCHIVECLOSEOUTVERIFYAUDITCLOSEOUTARCHIVEVERIFYJSON",
         "SHARDROUTEVERIFYREPORTARCHIVECLOSEOUTVERIFYAUDITCLOSEOUTARCHIVEVERIFYJSON", "read", false, false,
         true,
         "Read route preview verification report archive closeout verification audit closeout archive verification evidence without enabling active routing",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEARCHIVEMAINTJSON", "SHARDROUTEARCHIVEMAINTJSON", "read", false, false, true,
         "Read route preview archive maintenance ledger evidence without enabling active routing", Verb::RuntimeEvidence,
         false},
        {"SHARDROUTEARCHIVEMAINTVERIFYJSON", "SHARDROUTEARCHIVEMAINTVERIFYJSON", "read", false, false, true,
         "Read route preview archive maintenance verification evidence without enabling active routing",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEWORKSHEETVERIFYJSON", "SHARDROUTEWORKSHEETVERIFYJSON", "read", false, false, true,
         "Read route preview worksheet verification evidence without accepting manual values or enabling active routing",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEIMPORTPREFLIGHTJSON", "SHARDROUTEIMPORTPREFLIGHTJSON", "read", false, false, true,
         "Read route preview operator evidence import preflight without importing values or enabling active routing",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVALUEDRAFTJSON", "SHARDROUTEVALUEDRAFTJSON", "read", false, false, true,
         "Read route preview operator evidence value draft without accepting values or enabling active routing",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVALUESUPPLYJSON", "SHARDROUTEVALUESUPPLYJSON", "read", false, false, true,
         "Read route preview operator value-supply envelope without accepting values or enabling active routing",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVALUESUPPLYPRECHECKJSON", "SHARDROUTEVALUESUPPLYPRECHECKJSON", "read", false, false, true,
         "Read route preview operator value-supply approval precheck without accepting values or enabling active routing",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVALUESUPPLYAPPROVALTEMPLATEJSON", "SHARDROUTEVALUESUPPLYAPPROVALTEMPLATEJSON", "read",
         false, false, true,
         "Read route preview operator value-supply approval packet template without accepting values or enabling active routing",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVALUESUPPLYSIGNEDAPPROVALTEMPLATEJSON",
         "SHARDROUTEVALUESUPPLYSIGNEDAPPROVALTEMPLATEJSON", "read", false, false, true,
         "Read route preview operator value-supply signed approval template without capturing signatures or enabling active routing",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREPREFLIGHTJSON",
         "SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREPREFLIGHTJSON", "read", false, false, true,
         "Read route preview operator value-supply signed approval capture preflight without capturing signatures or enabling active routing",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTPREFLIGHTJSON",
         "SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTPREFLIGHTJSON", "read", false, false, true,
         "Read route preview operator value-supply signed approval capture artifact preflight without materializing artifacts or enabling active routing",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTDRAFTAUTHORINGREADINESSJSON",
         "SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTDRAFTAUTHORINGREADINESSJSON", "read", false, false,
         true,
         "Read route preview operator value-supply signed approval artifact draft authoring readiness without generating draft text or enabling execution",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTDRAFTINSTRUCTIONPREFLIGHTJSON",
         "SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTDRAFTINSTRUCTIONPREFLIGHTJSON", "read", false,
         false, true,
         "Read route preview operator value-supply signed approval artifact draft instruction preflight without materializing draft instructions or enabling execution",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTDRAFTTEXTPACKAGEREVIEWPREFLIGHTJSON",
         "SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTDRAFTTEXTPACKAGEREVIEWPREFLIGHTJSON", "read",
         false, false, true,
         "Read route preview operator value-supply signed approval artifact draft text package review preflight without parsing packages or enabling execution",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTDRAFTTEXTPACKAGEREVIEWCLOSEOUTAUDITJSON",
         "SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTDRAFTTEXTPACKAGEREVIEWCLOSEOUTAUDITJSON", "read",
         false, false, true,
         "Read route preview operator value-supply signed approval artifact draft text package review closeout audit without parsing packages or enabling execution",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTDRAFTTEXTPACKAGECOMPARISONCLOSEOUTAUDITJSON",
         "SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTDRAFTTEXTPACKAGECOMPARISONCLOSEOUTAUDITJSON",
         "read", false, false, true,
         "Read route preview operator value-supply signed approval artifact draft text package comparison closeout audit without parsing packages or enabling execution",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTDRAFTTEXTPACKAGECOMPAREDPACKAGEEVIDENCEINTAKEAUDITJSON",
         "SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTDRAFTTEXTPACKAGECOMPAREDPACKAGEEVIDENCEINTAKEAUDITJSON",
         "read", false, false, true,
         "Read route preview operator value-supply signed approval artifact draft text package compared package evidence intake audit without parsing packages or enabling execution",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTDRAFTTEXTPACKAGECANDIDATEDOCUMENTREQUESTPACKAGECLOSEOUTJSON",
         "SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTDRAFTTEXTPACKAGECANDIDATEDOCUMENTREQUESTPACKAGECLOSEOUTJSON",
         "read", false, false, true,
         "Read route preview candidate document request package closeout without creating documents or enabling execution",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTECANDIDATEREQUESTPACKAGEINTEGRITYJSON", "SHARDROUTECANDIDATEREQUESTPACKAGEINTEGRITYJSON",
         "read", false, false, true,
         "Read route preview candidate request package fixture integrity evidence without opening document intake",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTECANDIDATESUBMISSIONPRECHECKJSON", "SHARDROUTECANDIDATESUBMISSIONPRECHECKJSON", "read",
         false, false, true,
         "Read route preview candidate submission precheck handoff evidence without opening document intake",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTECANDIDATEINTAKEPACKETJSON", "SHARDROUTECANDIDATEINTAKEPACKETJSON", "read", false, false,
         true, "Read route preview candidate intake packet handoff evidence without opening document intake",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTECANDIDATEMATERIALREQUESTJSON", "SHARDROUTECANDIDATEMATERIALREQUESTJSON", "read", false,
         false, true, "Read route preview candidate material request closeout evidence without reading or accepting documents",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTECANDIDATEMATERIALREQUESTINTEGRITYJSON",
         "SHARDROUTECANDIDATEMATERIALREQUESTINTEGRITYJSON", "read", false, false, true,
         "Read route preview candidate material request fixture integrity evidence without consuming reviewed material",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTECANDIDATEMATERIALSUBMISSIONPRECHECKJSON",
         "SHARDROUTECANDIDATEMATERIALSUBMISSIONPRECHECKJSON", "read", false, false, true,
         "Read route preview candidate material submission precheck evidence without consuming reviewed material",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTECANDIDATEMATERIALSUBMISSIONPRECHECKINTEGRITYJSON",
         "SHARDROUTECANDIDATEMATERIALSUBMISSIONPRECHECKINTEGRITYJSON", "read", false, false, true,
         "Read route preview candidate material submission precheck fixture integrity evidence without opening material submission",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTECANDIDATEPROFILESECTIONJSON", "SHARDROUTECANDIDATEPROFILESECTIONJSON", "read", false,
         false, true, "Read route preview candidate document profile section renderer split evidence without starting services",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTDRAFTPROFILESECTIONJSON",
         "SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTDRAFTPROFILESECTIONJSON", "read", false, false,
         true, "Read route preview signed approval artifact draft profile section renderer split evidence without starting services",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTDRAFTPROFILESECTIONINTEGRITYJSON",
         "SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTDRAFTPROFILESECTIONINTEGRITYJSON", "read", false,
         false, true,
         "Read route preview signed approval artifact draft profile section integrity evidence without creating approvals",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTDRAFTTEXTPACKAGEPROFILESECTIONJSON",
         "SHARDROUTEVALUESUPPLYSIGNEDAPPROVALCAPTUREARTIFACTDRAFTTEXTPACKAGEPROFILESECTIONJSON", "read", false,
         false, true,
         "Read route preview signed approval artifact draft text package profile section renderer split evidence without parsing text packages or enabling execution",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVALUESUPPLYAPPROVALPROFILESECTIONJSON", "SHARDROUTEVALUESUPPLYAPPROVALPROFILESECTIONJSON",
         "read", false, false, true,
         "Read route preview operator value supply approval profile section renderer split evidence without importing approval material or enabling execution",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVALUESUPPLYPROFILESECTIONJSON", "SHARDROUTEVALUESUPPLYPROFILESECTIONJSON", "read", false,
         false, true,
         "Read route preview operator value supply profile section renderer split evidence without importing operator values or enabling execution",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEVALUESUPPLYPROFILESECTIONINTEGRITYJSON", "SHARDROUTEVALUESUPPLYPROFILESECTIONINTEGRITYJSON",
         "read", false, false, true,
         "Read route preview operator value supply profile section integrity evidence without importing operator values or enabling execution",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEPRODUCTIONLIVECAPTURENONPARTICIPATIONJSON",
         "SHARDROUTEPRODUCTIONLIVECAPTURENONPARTICIPATIONJSON", "read", false, false, true,
         "Read production live capture non-participation evidence without starting services, reading endpoints, or enabling execution",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEPRODUCTIONLIVECAPTUREARCHIVENONPARTICIPATIONJSON",
         "SHARDROUTEPRODUCTIONLIVECAPTUREARCHIVENONPARTICIPATIONJSON", "read", false, false, true,
         "Read production live capture archive non-participation evidence without loading archives, reading endpoints, or enabling execution",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEPRODUCTIONLIVECAPTUREARCHIVEVERIFYNONPARTICIPATIONJSON",
         "SHARDROUTEPRODUCTIONLIVECAPTUREARCHIVEVERIFYNONPARTICIPATIONJSON", "read", false, false, true,
         "Read production live capture archive verification non-participation evidence without reading verification endpoints, importing payloads, or enabling execution",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEPRODUCTIONLIVECAPTURERELEASEEVIDENCEREVIEWNONPARTICIPATIONJSON",
         "SHARDROUTEPRODUCTIONLIVECAPTURERELEASEEVIDENCEREVIEWNONPARTICIPATIONJSON", "read", false, false, true,
         "Read production live capture release evidence review non-participation evidence without reading review endpoints, importing payloads, or enabling execution",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTECATALOGENTRYGROUPSPLITNONPARTICIPATIONJSON",
         "SHARDROUTECATALOGENTRYGROUPSPLITNONPARTICIPATIONJSON", "read", false, false, true,
         "Read catalog entry group split non-participation evidence without reading catalog endpoints, importing catalog records, executing Node registries, or enabling writes",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEDISABLEDPRECHECKUPSTREAMECHONONPARTICIPATIONJSON",
         "SHARDROUTEDISABLEDPRECHECKUPSTREAMECHONONPARTICIPATIONJSON", "read", false, false, true,
         "Read disabled precheck upstream echo non-participation evidence without importing Node modules, reading endpoints or credentials, executing Node checks, or enabling writes",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTESANDBOXENDPOINTCREDENTIALRESOLVERUPSTREAMECHONONPARTICIPATIONJSON",
         "SHARDROUTESANDBOXENDPOINTCREDENTIALRESOLVERUPSTREAMECHONONPARTICIPATIONJSON", "read", false, false,
         true,
         "Read sandbox endpoint credential resolver upstream echo non-participation evidence without importing Node modules, reading endpoint handles, parsing raw endpoints, reading credentials, or enabling writes",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEIMPLEMENTATIONPLANUPSTREAMECHOCLOSEOUTNONPARTICIPATIONJSON",
         "SHARDROUTEIMPLEMENTATIONPLANUPSTREAMECHOCLOSEOUTNONPARTICIPATIONJSON", "read", false, false, true,
         "Read implementation-plan upstream echo closeout non-participation evidence without importing Node modules, reading endpoints or credentials, opening managed connections, or enabling writes",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTERELEASEWINDOWREADINESSPACKETSPLITNONPARTICIPATIONJSON",
         "SHARDROUTERELEASEWINDOWREADINESSPACKETSPLITNONPARTICIPATIONJSON", "read", false, false, true,
         "Read release-window readiness packet split non-participation evidence without importing Node packet modules, reading endpoints or credentials, replaying restore evidence, opening managed connections, or enabling writes",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEDISABLEDFAKEHARNESSCONTRACTUPSTREAMECHOVERIFICATIONSPLITNONPARTICIPATIONJSON",
         "SHARDROUTEDISABLEDFAKEHARNESSCONTRACTUPSTREAMECHOVERIFICATIONSPLITNONPARTICIPATIONJSON", "read",
         false, false, true,
         "Read disabled fake harness contract upstream echo verification split non-participation evidence without importing Node modules, parsing historical receipts, opening managed connections, or enabling writes",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEBLOCKEDEXECUTIONREHEARSALSPLITNONPARTICIPATIONJSON",
         "SHARDROUTEBLOCKEDEXECUTIONREHEARSALSPLITNONPARTICIPATIONJSON", "read", false, false, true,
         "Read blocked execution rehearsal split non-participation evidence without importing Node modules, parsing historical receipts, replaying WAL regression evidence, opening managed connections, or enabling writes",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTEPRECHECKUPSTREAMRECEIPTVERIFICATIONSPLITNONPARTICIPATIONJSON",
         "SHARDROUTEPRECHECKUPSTREAMRECEIPTVERIFICATIONSPLITNONPARTICIPATIONJSON", "read", false, false, true,
         "Read precheck upstream receipt verification split non-participation evidence without importing Node modules, parsing historical receipts, scanning Java evidence, executing downstream checks, mutating inventories, or enabling writes",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTERUNTIMEEXECUTIONPACKETAPPROVALGATEARCHIVEVERIFYNONPARTICIPATIONJSON",
         "SHARDROUTERUNTIMEEXECUTIONPACKETAPPROVALGATEARCHIVEVERIFYNONPARTICIPATIONJSON", "read", false,
         false, true,
         "Read runtime execution packet approval gate archive verification non-participation evidence without reading sibling archives, starting services, opening connections, or enabling execution",
         Verb::RuntimeEvidence, false},
        {"SHARDCODEWALKTHROUGHQUALITYGATENONPARTICIPATIONJSON",
         "SHARDCODEWALKTHROUGHQUALITYGATENONPARTICIPATIONJSON", "read", false, false, true,
         "Read code walkthrough quality gate non-participation evidence without reading Node walkthrough files, scanning sibling repositories, starting services, or enabling execution",
         Verb::RuntimeEvidence, false},
        {"SHARDPRODUCTIONSHARDEXECUTIONOWNERRECEIPTREQUESTPACKETJSON",
         "SHARDPRODUCTIONSHARDEXECUTIONOWNERRECEIPTREQUESTPACKETJSON", "read", false, false, true,
         "Read production shard execution owner receipt request packet evidence without claiming signed receipts, binding managed audit storage, starting services, routing writes, or enabling execution",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTETYPEBARRELSPLITNONPARTICIPATIONJSON",
         "SHARDROUTETYPEBARRELSPLITNONPARTICIPATIONJSON", "read", false, false, true,
         "Read type barrel split non-participation evidence without importing Node TypeScript types, reading profile endpoints, executing Node tests, or enabling writes",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTETYPEBARRELSPLITFOLLOWUPNONPARTICIPATIONJSON",
         "SHARDROUTETYPEBARRELSPLITFOLLOWUPNONPARTICIPATIONJSON", "read", false, false, true,
         "Read type barrel split follow-up non-participation evidence without importing Node TypeScript types, reading profile endpoints, executing Node checks, or enabling writes",
         Verb::RuntimeEvidence, false},
        {"SHARDROUTETYPEBARRELSPLITFOLLOWUPFIXTUREAUDITJSON",
         "SHARDROUTETYPEBARRELSPLITFOLLOWUPFIXTUREAUDITJSON", "read", false, false, true,
         "Read type barrel split follow-up fixture audit evidence without reading source fixture payloads at runtime, importing Node modules, executing Node checks, or enabling writes",
         Verb::RuntimeEvidence, false},
        {"COMMANDS", "COMMANDS", "meta", false, false, true, "Read command catalog as text",
         Verb::RuntimeEvidence, false},
        {"COMMANDSJSON", "COMMANDSJSON", "meta", false, false, true, "Read command catalog as JSON",
         Verb::RuntimeEvidence, false},
        {"EXPLAINJSON", "EXPLAINJSON command", "meta", false, false, true,
         "Explain a command risk profile as JSON without executing it", Verb::ExplainJson, false},
        {"CHECKJSON", "CHECKJSON command", "meta", false, false, true,
         "Read a write command execution contract as JSON without executing it", Verb::CheckJson, false},
        {"STORAGEJSON", "STORAGEJSON", "read", false, true, true, "Read storage evidence as JSON without mutating data",
         Verb::RuntimeEvidence, false},
        {"HELP", "HELP", "meta", false, false, true, "Show command help", Verb::Help, false},
        {"EXIT", "EXIT", "meta", false, false, true, "Close the current client session", Verb::Quit, false},
        {"QUIT", "QUIT", "meta", false, false, true, "Close the current client session", Verb::Quit, false},
    };
    return catalog;
}

} // namespace

const std::vector<CommandCatalogEntry>& entries() {
    return catalog_entries();
}

const CommandCatalogEntry* find(std::string_view command) {
    for (const auto& entry : entries()) {
        if (entry.name == command) {
            return &entry;
        }
    }
    return nullptr;
}

bool is_known(std::string_view command) {
    return find(command) != nullptr;
}

std::size_t count() {
    return entries().size();
}

CommandDispatchVerb lookup_dispatch_verb(std::string_view command) {
    const auto* entry = find(command);
    return entry == nullptr ? CommandDispatchVerb::Unknown : entry->dispatch_verb;
}

bool is_key_completion_command(std::string_view command) {
    const auto* entry = find(command);
    return entry != nullptr && entry->key_completion;
}

std::vector<std::string> command_names() {
    std::vector<std::string> names;
    names.reserve(entries().size());
    for (const auto& entry : entries()) {
        names.emplace_back(entry.name);
    }
    return names;
}

std::string help_text() {
    std::string result = "Commands:";
    for (const auto& entry : entries()) {
        result += "\n  ";
        result += entry.usage;
    }
    return result;
}

} // namespace minikv::command_catalog
