#include "minikv/shard_readiness_boundary_fields.hpp"

#include "minikv/runtime_evidence.hpp"

#include <string>
#include <vector>

namespace minikv::shard_readiness::boundary_fields {
namespace {

std::string json_string_array(const std::vector<std::string>& values) {
    return runtime_evidence::json_string_array(values);
}

} // namespace

std::string format_catalog_maintenance_json() {
    return "{\"maintenanceMode\":\"boundary-field-catalog-split-contract-preserving\","
           "\"sourceNodePlan\":\"docs/plans3/v418-post-sandbox-endpoint-credential-resolver-route-group-split-roadmap.md\","
           "\"sourceFrozenReleaseVersion\":\"v159\","
           "\"sourceFrozenFixturePath\":\"fixtures/release/shard-readiness-v159.json\","
           "\"boundaryFieldCatalogExtracted\":true,"
           "\"readOnlyBoundaryFieldsStillPublished\":true,"
           "\"publicShardJsonContractChanged\":false,"
           "\"fixturePathChanged\":false,"
           "\"shardJsonCommandChanged\":false,"
           "\"nodeRouteGroupSplitCompatibilityPreserved\":true,"
           "\"nodeAddsEvidenceGate\":false,"
           "\"runtimeGateApprovalPresent\":false,"
           "\"runtimeExecutionPacketPresent\":false,"
           "\"runtimeExecutionPacketExecutable\":false,"
           "\"startsJavaService\":false,"
           "\"startsMiniKvService\":false,"
           "\"startsServices\":false,"
           "\"runtimeProbeAllowed\":false,"
           "\"liveReadAllowed\":false,"
           "\"activeShardPrototypeEnabled\":false,"
           "\"routerActivationAllowed\":false,"
           "\"writeRoutingAllowed\":false,"
           "\"writeCommandsAllowed\":false,"
           "\"adminCommandsAllowed\":false,"
           "\"loadRestoreCompactAllowed\":false,"
           "\"executionAllowed\":false,"
           "\"readOnly\":true}";
}

namespace {

const std::vector<std::string>& read_only_boundary_field_names() {
    static const std::vector<std::string> fields = {
        "readOnly",
        "executionAllowed",
        "slotTablePreview.slotTablePreviewOnly",
        "slotTablePreview.readOnlyShardMapPreview",
        "slotTablePreview.activeRouterInstalled",
        "slotTablePreview.routerActivationAllowed",
        "slotTablePreview.writeRoutingAllowed",
        "slotTablePreview.writeCommandsAllowed",
        "slotTablePreview.adminCommandsAllowed",
        "slotTablePreview.loadRestoreCompactAllowed",
        "slotTablePreview.storageDirectoriesCreated",
        "slotTablePreview.startsServices",
        "slotTablePreview.runtimeProbeAllowed",
        "slotTablePreview.liveReadAllowed",
        "slotTablePreview.executionAllowed",
        "slotTablePreviewAudit.contiguousSlotRange",
        "slotTablePreviewAudit.duplicateSlotsDetected",
        "slotTablePreviewAudit.unassignedSlotsDetected",
        "slotTablePreviewAudit.allSlotsMapped",
        "slotTablePreviewAudit.allAssignmentsReadOnly",
        "slotTablePreviewAudit.allAssignmentsPreviewOnly",
        "slotTablePreviewAudit.activeRouterInstalled",
        "slotTablePreviewAudit.routerActivationAllowed",
        "slotTablePreviewAudit.writeRoutingAllowed",
        "slotTablePreviewAudit.writeCommandsAllowed",
        "slotTablePreviewAudit.adminCommandsAllowed",
        "slotTablePreviewAudit.loadRestoreCompactAllowed",
        "slotTablePreviewAudit.startsServices",
        "slotTablePreviewAudit.runtimeProbeAllowed",
        "slotTablePreviewAudit.liveReadAllowed",
        "slotTablePreviewAudit.executionAllowed",
        "slotTablePreviewAuditMaintenance.publicShardJsonContractChanged",
        "slotTablePreviewAuditMaintenance.fixturePathChanged",
        "slotTablePreviewAuditMaintenance.shardJsonCommandChanged",
        "slotTablePreviewAuditMaintenance.nodeAddsEvidenceGate",
        "slotTablePreviewAuditMaintenance.runtimeGateApprovalPresent",
        "slotTablePreviewAuditMaintenance.runtimeExecutionPacketExecutable",
        "slotTablePreviewAuditMaintenance.startsJavaService",
        "slotTablePreviewAuditMaintenance.startsMiniKvService",
        "slotTablePreviewAuditMaintenance.startsServices",
        "slotTablePreviewAuditMaintenance.runtimeProbeAllowed",
        "slotTablePreviewAuditMaintenance.liveReadAllowed",
        "slotTablePreviewAuditMaintenance.activeRouterInstalled",
        "slotTablePreviewAuditMaintenance.routerActivationAllowed",
        "slotTablePreviewAuditMaintenance.writeRoutingAllowed",
        "slotTablePreviewAuditMaintenance.writeCommandsAllowed",
        "slotTablePreviewAuditMaintenance.adminCommandsAllowed",
        "slotTablePreviewAuditMaintenance.loadRestoreCompactAllowed",
        "slotTablePreviewAuditMaintenance.executionAllowed",
        "shardReadinessReleaseCatalog.publicShardJsonContractChanged",
        "shardReadinessReleaseCatalog.fixturePathChanged",
        "shardReadinessReleaseCatalog.shardJsonCommandChanged",
        "shardReadinessReleaseCatalog.nodeAddsEvidenceGate",
        "shardReadinessReleaseCatalog.versionedFixtureCatalogOnly",
        "shardReadinessReleaseCatalog.rollingCurrentUsedForFrozenCatalog",
        "shardReadinessReleaseCatalog.runtimeGateApprovalPresent",
        "shardReadinessReleaseCatalog.runtimeExecutionPacketExecutable",
        "shardReadinessReleaseCatalog.startsJavaService",
        "shardReadinessReleaseCatalog.startsMiniKvService",
        "shardReadinessReleaseCatalog.startsServices",
        "shardReadinessReleaseCatalog.runtimeProbeAllowed",
        "shardReadinessReleaseCatalog.liveReadAllowed",
        "shardReadinessReleaseCatalog.activeRouterInstalled",
        "shardReadinessReleaseCatalog.routerActivationAllowed",
        "shardReadinessReleaseCatalog.writeRoutingAllowed",
        "shardReadinessReleaseCatalog.writeCommandsAllowed",
        "shardReadinessReleaseCatalog.adminCommandsAllowed",
        "shardReadinessReleaseCatalog.loadRestoreCompactAllowed",
        "shardReadinessReleaseCatalog.executionAllowed",
        "shardReadinessReleaseCatalogAudit.contiguousReleaseRange",
        "shardReadinessReleaseCatalogAudit.duplicateReleasesDetected",
        "shardReadinessReleaseCatalogAudit.missingCatalogEntriesDetected",
        "shardReadinessReleaseCatalogAudit.allCatalogedDigestsPresent",
        "shardReadinessReleaseCatalogAudit.allCatalogedFixturesVersioned",
        "shardReadinessReleaseCatalogAudit.allCatalogedEntriesReadOnly",
        "shardReadinessReleaseCatalogAudit.fieldCountsMonotonic",
        "shardReadinessReleaseCatalogAudit.groupCountsMonotonic",
        "shardReadinessReleaseCatalogAudit.latestDigestMatchesFrozenSource",
        "shardReadinessReleaseCatalogAudit.catalogOnlyAudit",
        "shardReadinessReleaseCatalogAudit.runtimeGateApprovalPresent",
        "shardReadinessReleaseCatalogAudit.runtimeExecutionPacketExecutable",
        "shardReadinessReleaseCatalogAudit.startsJavaService",
        "shardReadinessReleaseCatalogAudit.startsMiniKvService",
        "shardReadinessReleaseCatalogAudit.startsServices",
        "shardReadinessReleaseCatalogAudit.runtimeProbeAllowed",
        "shardReadinessReleaseCatalogAudit.liveReadAllowed",
        "shardReadinessReleaseCatalogAudit.activeRouterInstalled",
        "shardReadinessReleaseCatalogAudit.routerActivationAllowed",
        "shardReadinessReleaseCatalogAudit.writeRoutingAllowed",
        "shardReadinessReleaseCatalogAudit.writeCommandsAllowed",
        "shardReadinessReleaseCatalogAudit.adminCommandsAllowed",
        "shardReadinessReleaseCatalogAudit.loadRestoreCompactAllowed",
        "shardReadinessReleaseCatalogAudit.executionAllowed",
        "boundaries.writeCommandsAllowed",
        "boundaries.adminCommandsAllowed",
        "boundaries.loadRestoreCompactAllowed",
        "boundaries.archivedNodeEvidenceMutated",
        "archiveCompatibility.changesArchivedNodeEvidence",
        "historicalFallback.rollingCurrentUsedForHistoricalBaseline",
        "activePrototypePlan.activeShardPrototypeAllowed",
        "activePrototypePlan.routerActivationAllowed",
        "activePrototypePlan.shardDirectoryCreationAllowed",
        "activePrototypePlan.writeRoutingAllowed",
        "activePrototypePlanFreeze.rollingCurrentUsedForFrozenBaseline",
        "activePrototypePlanFreeze.frozenRouterActivationAllowed",
        "activePrototypePlanFreeze.frozenWriteRoutingAllowed",
        "consumerHandoff.startsServices",
        "consumerHandoff.routerActivationAllowed",
        "consumerHandoff.writeRoutingAllowed",
        "consumerHandoff.executionAllowed",
        "liveReadGatePlan.liveReadGateAllowed",
        "liveReadGatePlan.runtimeProbeAllowed",
        "liveReadGatePlan.startsServices",
        "liveReadGatePlan.routerActivationAllowed",
        "liveReadGatePlan.writeRoutingAllowed",
        "liveReadGatePlan.executionAllowed",
        "liveReadGatePlanFreeze.rollingCurrentUsedForFrozenBaseline",
        "liveReadGatePlanFreeze.frozenRuntimeProbeAllowed",
        "liveReadGatePlanFreeze.frozenStartsServices",
        "liveReadGatePlanFreeze.frozenExecutionAllowed",
        "operatorServiceLifecycleTemplate.serviceOwnerDeclared",
        "operatorServiceLifecycleTemplate.startupCommandDeclared",
        "operatorServiceLifecycleTemplate.portListDeclared",
        "operatorServiceLifecycleTemplate.getOnlySmokeTargetDeclared",
        "operatorServiceLifecycleTemplate.startsServices",
        "operatorServiceLifecycleTemplate.runtimeProbeAllowed",
        "operatorServiceLifecycleTemplate.liveReadAllowed",
        "operatorServiceLifecycleTemplate.executionAllowed",
        "operatorServiceLifecycleTemplateFreeze.rollingCurrentUsedForFrozenBaseline",
        "operatorServiceLifecycleTemplateFreeze.frozenRuntimeProbeAllowed",
        "operatorServiceLifecycleTemplateFreeze.frozenExecutionAllowed",
        "operatorServiceLifecycleEvidence.runtimeGateApproved",
        "operatorServiceLifecycleEvidence.startsServices",
        "operatorServiceLifecycleEvidence.runtimeProbeAllowed",
        "operatorServiceLifecycleEvidence.liveReadAllowed",
        "operatorServiceLifecycleEvidence.routerActivationAllowed",
        "operatorServiceLifecycleEvidence.writeRoutingAllowed",
        "operatorServiceLifecycleEvidence.executionAllowed",
        "operatorServiceLifecycleEvidenceFreeze.rollingCurrentUsedForFrozenBaseline",
        "operatorServiceLifecycleEvidenceFreeze.frozenRuntimeGateApproved",
        "operatorServiceLifecycleEvidenceFreeze.frozenStartsServices",
        "operatorServiceLifecycleEvidenceFreeze.frozenRuntimeProbeAllowed",
        "operatorServiceLifecycleEvidenceFreeze.frozenLiveReadAllowed",
        "operatorServiceLifecycleEvidenceFreeze.frozenRouterActivationAllowed",
        "operatorServiceLifecycleEvidenceFreeze.frozenWriteRoutingAllowed",
        "operatorServiceLifecycleEvidenceFreeze.frozenExecutionAllowed",
        "runtimeExecutionArtifactIntakePreflight.readyForRuntimeExecutionPacket",
        "runtimeExecutionArtifactIntakePreflight.readyForRuntimeLiveReadGate",
        "runtimeExecutionArtifactIntakePreflight.runtimeExecutionArtifactsComplete",
        "runtimeExecutionArtifactIntakePreflight.runtimeExecutionPacketPresent",
        "runtimeExecutionArtifactIntakePreflight.runtimeExecutionPacketExecutable",
        "runtimeExecutionArtifactIntakePreflight.executionAttempted",
        "runtimeExecutionArtifactIntakePreflight.startsMiniKvService",
        "runtimeExecutionArtifactIntakePreflight.startsServices",
        "runtimeExecutionArtifactIntakePreflight.runtimeProbeAllowed",
        "runtimeExecutionArtifactIntakePreflight.liveReadAllowed",
        "runtimeExecutionArtifactIntakePreflight.routerActivationAllowed",
        "runtimeExecutionArtifactIntakePreflight.writeRoutingAllowed",
        "runtimeExecutionArtifactIntakePreflight.executionAllowed",
        "runtimeExecutionArtifactIntakePreflightFreeze.rollingCurrentUsedForFrozenBaseline",
        "runtimeExecutionArtifactIntakePreflightFreeze.frozenRuntimeExecutionArtifactsComplete",
        "runtimeExecutionArtifactIntakePreflightFreeze.frozenRuntimeExecutionPacketExecutable",
        "runtimeExecutionArtifactIntakePreflightFreeze.frozenExecutionAttempted",
        "runtimeExecutionArtifactIntakePreflightFreeze.frozenStartsMiniKvService",
        "runtimeExecutionArtifactIntakePreflightFreeze.frozenRuntimeProbeAllowed",
        "runtimeExecutionArtifactIntakePreflightFreeze.frozenLiveReadAllowed",
        "runtimeExecutionArtifactIntakePreflightFreeze.frozenRouterActivationAllowed",
        "runtimeExecutionArtifactIntakePreflightFreeze.frozenWriteRoutingAllowed",
        "runtimeExecutionArtifactIntakePreflightFreeze.frozenExecutionAllowed",
        "miniKvRuntimeExecutionArtifactCandidate.acceptedRuntimeExecutionArtifactsComplete",
        "miniKvRuntimeExecutionArtifactCandidate.operatorApprovalRecordPresent",
        "miniKvRuntimeExecutionArtifactCandidate.nodeRuntimeWindowApproved",
        "miniKvRuntimeExecutionArtifactCandidate.crossProjectRuntimeExecutionPacketPresent",
        "miniKvRuntimeExecutionArtifactCandidate.javaPortBindingPresent",
        "miniKvRuntimeExecutionArtifactCandidate.miniKvLoopbackPortOperatorApproved",
        "miniKvRuntimeExecutionArtifactCandidate.getOnlySmokeCommandOperatorApproved",
        "miniKvRuntimeExecutionArtifactCandidate.serviceOwnerOperatorConfirmed",
        "miniKvRuntimeExecutionArtifactCandidate.cleanupProofPresent",
        "miniKvRuntimeExecutionArtifactCandidate.runtimeExecutionPacketExecutable",
        "miniKvRuntimeExecutionArtifactCandidate.startsMiniKvService",
        "miniKvRuntimeExecutionArtifactCandidate.startsServices",
        "miniKvRuntimeExecutionArtifactCandidate.runtimeProbeAllowed",
        "miniKvRuntimeExecutionArtifactCandidate.liveReadAllowed",
        "miniKvRuntimeExecutionArtifactCandidate.routerActivationAllowed",
        "miniKvRuntimeExecutionArtifactCandidate.writeRoutingAllowed",
        "miniKvRuntimeExecutionArtifactCandidate.executionAllowed",
        "miniKvRuntimeExecutionArtifactCandidateFreeze.rollingCurrentUsedForFrozenBaseline",
        "miniKvRuntimeExecutionArtifactCandidateFreeze.frozenAcceptedRuntimeExecutionArtifactsComplete",
        "miniKvRuntimeExecutionArtifactCandidateFreeze.frozenRuntimeExecutionPacketExecutable",
        "miniKvRuntimeExecutionArtifactCandidateFreeze.frozenStartsMiniKvService",
        "miniKvRuntimeExecutionArtifactCandidateFreeze.frozenRuntimeProbeAllowed",
        "miniKvRuntimeExecutionArtifactCandidateFreeze.frozenLiveReadAllowed",
        "miniKvRuntimeExecutionArtifactCandidateFreeze.frozenRouterActivationAllowed",
        "miniKvRuntimeExecutionArtifactCandidateFreeze.frozenWriteRoutingAllowed",
        "miniKvRuntimeExecutionArtifactCandidateFreeze.frozenExecutionAllowed",
        "runtimeExecutionApprovalGateInputPrecheck.nodeApprovedRuntimeWindowPresent",
        "runtimeExecutionApprovalGateInputPrecheck.correlatedOperatorApprovalRecordPresent",
        "runtimeExecutionApprovalGateInputPrecheck.completeCrossProjectRuntimeExecutionPacketPresent",
        "runtimeExecutionApprovalGateInputPrecheck.approvalGateInputsComplete",
        "runtimeExecutionApprovalGateInputPrecheck.runtimeGateApprovalPresent",
        "runtimeExecutionApprovalGateInputPrecheck.readyForRuntimeExecutionPacket",
        "runtimeExecutionApprovalGateInputPrecheck.readyForRuntimeLiveReadGate",
        "runtimeExecutionApprovalGateInputPrecheck.runtimeExecutionArtifactsComplete",
        "runtimeExecutionApprovalGateInputPrecheck.runtimeExecutionPacketPresent",
        "runtimeExecutionApprovalGateInputPrecheck.runtimeExecutionPacketExecutable",
        "runtimeExecutionApprovalGateInputPrecheck.concreteLoopbackPortsAssigned",
        "runtimeExecutionApprovalGateInputPrecheck.executionAttempted",
        "runtimeExecutionApprovalGateInputPrecheck.startsJavaService",
        "runtimeExecutionApprovalGateInputPrecheck.startsMiniKvService",
        "runtimeExecutionApprovalGateInputPrecheck.startsServices",
        "runtimeExecutionApprovalGateInputPrecheck.runtimeProbeAllowed",
        "runtimeExecutionApprovalGateInputPrecheck.liveReadAllowed",
        "runtimeExecutionApprovalGateInputPrecheck.routerActivationAllowed",
        "runtimeExecutionApprovalGateInputPrecheck.writeRoutingAllowed",
        "runtimeExecutionApprovalGateInputPrecheck.executionAllowed",
        "runtimeExecutionApprovalGateInputPrecheckFreeze.rollingCurrentUsedForFrozenBaseline",
        "runtimeExecutionApprovalGateInputPrecheckFreeze.frozenApprovalGateInputsComplete",
        "runtimeExecutionApprovalGateInputPrecheckFreeze.frozenRuntimeGateApprovalPresent",
        "runtimeExecutionApprovalGateInputPrecheckFreeze.frozenRuntimeExecutionPacketExecutable",
        "runtimeExecutionApprovalGateInputPrecheckFreeze.frozenConcreteLoopbackPortsAssigned",
        "runtimeExecutionApprovalGateInputPrecheckFreeze.frozenExecutionAttempted",
        "runtimeExecutionApprovalGateInputPrecheckFreeze.frozenStartsJavaService",
        "runtimeExecutionApprovalGateInputPrecheckFreeze.frozenStartsMiniKvService",
        "runtimeExecutionApprovalGateInputPrecheckFreeze.frozenRuntimeProbeAllowed",
        "runtimeExecutionApprovalGateInputPrecheckFreeze.frozenLiveReadAllowed",
        "runtimeExecutionApprovalGateInputPrecheckFreeze.frozenRouterActivationAllowed",
        "runtimeExecutionApprovalGateInputPrecheckFreeze.frozenWriteRoutingAllowed",
        "runtimeExecutionApprovalGateInputPrecheckFreeze.frozenExecutionAllowed",
        "miniKvFinalApprovalGateInput.cleanupProofPresent",
        "miniKvFinalApprovalGateInput.nodeApprovedRuntimeWindowPresent",
        "miniKvFinalApprovalGateInput.correlatedOperatorApprovalRecordPresent",
        "miniKvFinalApprovalGateInput.completeCrossProjectRuntimeExecutionPacketPresent",
        "miniKvFinalApprovalGateInput.runtimeGateApprovalPresent",
        "miniKvFinalApprovalGateInput.readyForRuntimeExecutionPacket",
        "miniKvFinalApprovalGateInput.readyForRuntimeLiveReadGate",
        "miniKvFinalApprovalGateInput.runtimeExecutionPacketExecutable",
        "miniKvFinalApprovalGateInput.concreteLoopbackPortsAssignedByCrossProjectPacket",
        "miniKvFinalApprovalGateInput.executionAttempted",
        "miniKvFinalApprovalGateInput.startsJavaService",
        "miniKvFinalApprovalGateInput.startsMiniKvService",
        "miniKvFinalApprovalGateInput.startsServices",
        "miniKvFinalApprovalGateInput.runtimeProbeAllowed",
        "miniKvFinalApprovalGateInput.liveReadAllowed",
        "miniKvFinalApprovalGateInput.routerActivationAllowed",
        "miniKvFinalApprovalGateInput.writeRoutingAllowed",
        "miniKvFinalApprovalGateInput.executionAllowed",
        "miniKvFinalApprovalGateInputFreeze.rollingCurrentUsedForFrozenBaseline",
        "miniKvFinalApprovalGateInputFreeze.frozenCleanupProofPresent",
        "miniKvFinalApprovalGateInputFreeze.frozenRuntimeGateApprovalPresent",
        "miniKvFinalApprovalGateInputFreeze.frozenReadyForRuntimeExecutionPacket",
        "miniKvFinalApprovalGateInputFreeze.frozenReadyForRuntimeLiveReadGate",
        "miniKvFinalApprovalGateInputFreeze.frozenRuntimeExecutionPacketExecutable",
        "miniKvFinalApprovalGateInputFreeze.frozenStartsJavaService",
        "miniKvFinalApprovalGateInputFreeze.frozenStartsMiniKvService",
        "miniKvFinalApprovalGateInputFreeze.frozenRuntimeProbeAllowed",
        "miniKvFinalApprovalGateInputFreeze.frozenLiveReadAllowed",
        "miniKvFinalApprovalGateInputFreeze.frozenRouterActivationAllowed",
        "miniKvFinalApprovalGateInputFreeze.frozenWriteRoutingAllowed",
        "miniKvFinalApprovalGateInputFreeze.frozenExecutionAllowed",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.canonicalRuntimeInputPresent",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.templateCopiedToCanonicalInput",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.nodeApprovedRuntimeWindowCanonicalPresent",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.correlatedOperatorApprovalRecordCanonicalPresent",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.completeCrossProjectRuntimeExecutionPacketCanonicalPresent",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.sharedApprovalCorrelationIdPresent",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.templatesAuthorizeRuntime",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.templateDigestAcceptedAsApproval",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.writesCanonicalApprovalInputFiles",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.changesNodeInputTemplateFiles",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.runtimeExecutionPacketPresent",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.runtimeExecutionPacketExecutable",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.runtimeGateApprovalPresent",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.readyForRuntimeExecutionPacket",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.readyForRuntimeLiveReadGate",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.concreteLoopbackPortsAssigned",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.executionAttempted",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.startsJavaService",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.startsMiniKvService",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.runtimeProbeAllowed",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.liveReadAllowed",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.routerActivationAllowed",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.writeRoutingAllowed",
        "runtimeExecutionApprovalInputTemplateValidatorEcho.executionAllowed",
        "runtimeExecutionApprovalInputTemplateValidatorEchoFreeze.rollingCurrentUsedForFrozenBaseline",
        "runtimeExecutionApprovalInputTemplateValidatorEchoFreeze.frozenCanonicalRuntimeInputPresent",
        "runtimeExecutionApprovalInputTemplateValidatorEchoFreeze.frozenTemplateCopiedToCanonicalInput",
        "runtimeExecutionApprovalInputTemplateValidatorEchoFreeze.frozenSharedApprovalCorrelationIdPresent",
        "runtimeExecutionApprovalInputTemplateValidatorEchoFreeze.frozenTemplatesAuthorizeRuntime",
        "runtimeExecutionApprovalInputTemplateValidatorEchoFreeze.frozenTemplateDigestAcceptedAsApproval",
        "runtimeExecutionApprovalInputTemplateValidatorEchoFreeze.frozenWritesCanonicalApprovalInputFiles",
        "runtimeExecutionApprovalInputTemplateValidatorEchoFreeze.frozenChangesNodeInputTemplateFiles",
        "runtimeExecutionApprovalInputTemplateValidatorEchoFreeze.frozenRuntimeExecutionPacketExecutable",
        "runtimeExecutionApprovalInputTemplateValidatorEchoFreeze.frozenStartsJavaService",
        "runtimeExecutionApprovalInputTemplateValidatorEchoFreeze.frozenStartsMiniKvService",
        "runtimeExecutionApprovalInputTemplateValidatorEchoFreeze.frozenRuntimeProbeAllowed",
        "runtimeExecutionApprovalInputTemplateValidatorEchoFreeze.frozenLiveReadAllowed",
        "runtimeExecutionApprovalInputTemplateValidatorEchoFreeze.frozenRouterActivationAllowed",
        "runtimeExecutionApprovalInputTemplateValidatorEchoFreeze.frozenWriteRoutingAllowed",
        "runtimeExecutionApprovalInputTemplateValidatorEchoFreeze.frozenExecutionAllowed",
        "runtimeExecutionCanonicalApprovalInputPrecheck.nodeApprovedRuntimeWindowCanonicalPresent",
        "runtimeExecutionCanonicalApprovalInputPrecheck.correlatedOperatorApprovalRecordCanonicalPresent",
        "runtimeExecutionCanonicalApprovalInputPrecheck.completeCrossProjectRuntimeExecutionPacketCanonicalPresent",
        "runtimeExecutionCanonicalApprovalInputPrecheck.canonicalApprovalInputsComplete",
        "runtimeExecutionCanonicalApprovalInputPrecheck.sharedApprovalCorrelationIdPresent",
        "runtimeExecutionCanonicalApprovalInputPrecheck.sharedApprovalCorrelationIdValidated",
        "runtimeExecutionCanonicalApprovalInputPrecheck.templatesAcceptedAsCanonicalInputs",
        "runtimeExecutionCanonicalApprovalInputPrecheck.templateCompatibilityEvidenceAcceptedAsApproval",
        "runtimeExecutionCanonicalApprovalInputPrecheck.runtimeGateApprovalPresent",
        "runtimeExecutionCanonicalApprovalInputPrecheck.runtimeExecutionPacketPresent",
        "runtimeExecutionCanonicalApprovalInputPrecheck.runtimeExecutionPacketExecutable",
        "runtimeExecutionCanonicalApprovalInputPrecheck.readyForRuntimeExecutionPacket",
        "runtimeExecutionCanonicalApprovalInputPrecheck.readyForRuntimeLiveReadGate",
        "runtimeExecutionCanonicalApprovalInputPrecheck.concreteLoopbackPortsAssigned",
        "runtimeExecutionCanonicalApprovalInputPrecheck.executionAttempted",
        "runtimeExecutionCanonicalApprovalInputPrecheck.startsJavaService",
        "runtimeExecutionCanonicalApprovalInputPrecheck.startsMiniKvService",
        "runtimeExecutionCanonicalApprovalInputPrecheck.runtimeProbeAllowed",
        "runtimeExecutionCanonicalApprovalInputPrecheck.liveReadAllowed",
        "runtimeExecutionCanonicalApprovalInputPrecheck.routerActivationAllowed",
        "runtimeExecutionCanonicalApprovalInputPrecheck.writeRoutingAllowed",
        "runtimeExecutionCanonicalApprovalInputPrecheck.executionAllowed",
        "nodeRouteGroupSplitCompatibility.nodeApiPathChanged",
        "nodeRouteGroupSplitCompatibility.nodeResponseShapeChanged",
        "nodeRouteGroupSplitCompatibility.nodeAddsEvidenceGate",
        "nodeRouteGroupSplitCompatibility.nodeStartsJavaService",
        "nodeRouteGroupSplitCompatibility.nodeStartsMiniKvService",
        "nodeRouteGroupSplitCompatibility.miniKvContractChangedForNodeRouteSplit",
        "nodeRouteGroupSplitCompatibility.miniKvFixturePathChanged",
        "nodeRouteGroupSplitCompatibility.miniKvShardJsonCommandChanged",
        "nodeRouteGroupSplitCompatibility.miniKvRequiresNodeRouteTableChange",
        "nodeRouteGroupSplitCompatibility.runtimeGateApprovalPresent",
        "nodeRouteGroupSplitCompatibility.runtimeExecutionPacketPresent",
        "nodeRouteGroupSplitCompatibility.runtimeExecutionPacketExecutable",
        "nodeRouteGroupSplitCompatibility.readyForRuntimeExecutionPacket",
        "nodeRouteGroupSplitCompatibility.readyForRuntimeLiveReadGate",
        "nodeRouteGroupSplitCompatibility.canonicalApprovalInputsComplete",
        "nodeRouteGroupSplitCompatibility.templatesAcceptedAsCanonicalInputs",
        "nodeRouteGroupSplitCompatibility.executionAttempted",
        "nodeRouteGroupSplitCompatibility.startsJavaService",
        "nodeRouteGroupSplitCompatibility.startsMiniKvService",
        "nodeRouteGroupSplitCompatibility.runtimeProbeAllowed",
        "nodeRouteGroupSplitCompatibility.liveReadAllowed",
        "nodeRouteGroupSplitCompatibility.routerActivationAllowed",
        "nodeRouteGroupSplitCompatibility.writeRoutingAllowed",
        "nodeRouteGroupSplitCompatibility.executionAllowed",
        "boundaryCatalogMaintenance.publicShardJsonContractChanged",
        "boundaryCatalogMaintenance.fixturePathChanged",
        "boundaryCatalogMaintenance.shardJsonCommandChanged",
        "boundaryCatalogMaintenance.nodeAddsEvidenceGate",
        "boundaryCatalogMaintenance.runtimeGateApprovalPresent",
        "boundaryCatalogMaintenance.runtimeExecutionPacketExecutable",
        "boundaryCatalogMaintenance.startsJavaService",
        "boundaryCatalogMaintenance.startsMiniKvService",
        "boundaryCatalogMaintenance.startsServices",
        "boundaryCatalogMaintenance.runtimeProbeAllowed",
        "boundaryCatalogMaintenance.liveReadAllowed",
        "boundaryCatalogMaintenance.activeShardPrototypeEnabled",
        "boundaryCatalogMaintenance.routerActivationAllowed",
        "boundaryCatalogMaintenance.writeRoutingAllowed",
        "boundaryCatalogMaintenance.writeCommandsAllowed",
        "boundaryCatalogMaintenance.adminCommandsAllowed",
        "boundaryCatalogMaintenance.loadRestoreCompactAllowed",
        "boundaryCatalogMaintenance.executionAllowed",
        "boundaryCatalogIndex.publicShardJsonContractChanged",
        "boundaryCatalogIndex.fixturePathChanged",
        "boundaryCatalogIndex.shardJsonCommandChanged",
        "boundaryCatalogIndex.nodeAddsEvidenceGate",
        "boundaryCatalogIndex.runtimeGateApprovalPresent",
        "boundaryCatalogIndex.runtimeExecutionPacketExecutable",
        "boundaryCatalogIndex.startsJavaService",
        "boundaryCatalogIndex.startsMiniKvService",
        "boundaryCatalogIndex.startsServices",
        "boundaryCatalogIndex.runtimeProbeAllowed",
        "boundaryCatalogIndex.liveReadAllowed",
        "boundaryCatalogIndex.activeShardPrototypeEnabled",
        "boundaryCatalogIndex.routerActivationAllowed",
        "boundaryCatalogIndex.writeRoutingAllowed",
        "boundaryCatalogIndex.writeCommandsAllowed",
        "boundaryCatalogIndex.adminCommandsAllowed",
        "boundaryCatalogIndex.loadRestoreCompactAllowed",
        "boundaryCatalogIndex.executionAllowed",
    };
    return fields;
}

const std::vector<std::string>& boundary_catalog_groups() {
    static const std::vector<std::string> groups = {
        "top-level-read-only",
        "slot-table-preview",
        "slot-table-preview-audit",
        "slot-table-preview-audit-maintenance",
        "shard-readiness-release-catalog",
        "shard-readiness-release-catalog-audit",
        "core-boundaries",
        "historical-fallback",
        "active-prototype-plan",
        "consumer-handoff",
        "live-read-gate",
        "operator-service-lifecycle",
        "runtime-execution-artifacts",
        "approval-gate-inputs",
        "final-mini-kv-approval-input",
        "template-validator-echo",
        "canonical-approval-input-precheck",
        "node-route-group-split-compatibility",
        "boundary-catalog-maintenance",
        "boundary-catalog-index",
    };
    return groups;
}

} // namespace

std::string format_catalog_index_json() {
    const auto& fields = read_only_boundary_field_names();
    const auto& groups = boundary_catalog_groups();
    return std::string{"{\"catalogVersion\":\"read-only-boundary-fields.v7\","} +
           "\"sourceNodePlan\":\"docs/plans3/v432-post-credential-resolver-endpoint-handle-allowlist-approval-route-group-split-roadmap.md\","
           "\"sourceFrozenReleaseVersion\":\"v165\","
           "\"sourceFrozenFixturePath\":\"fixtures/release/shard-readiness-v165.json\","
           "\"fieldCount\":" + std::to_string(fields.size()) +
           ",\"groupCount\":" + std::to_string(groups.size()) +
           ",\"fieldListGeneratedFromSharedVector\":true,"
           "\"catalogGroups\":" + json_string_array(groups) +
           ",\"slotTablePreviewCataloged\":true"
           ",\"slotTablePreviewAuditCataloged\":true"
           ",\"slotTablePreviewAuditMaintenanceCataloged\":true"
           ",\"shardReadinessReleaseCatalogCataloged\":true"
           ",\"shardReadinessReleaseCatalogAuditCataloged\":true"
           ",\"readOnlyBoundaryFieldsStillPublished\":true,"
           "\"boundaryCatalogMaintenancePreserved\":true,"
           "\"publicShardJsonContractChanged\":false,"
           "\"fixturePathChanged\":false,"
           "\"shardJsonCommandChanged\":false,"
           "\"nodeAddsEvidenceGate\":false,"
           "\"runtimeGateApprovalPresent\":false,"
           "\"runtimeExecutionPacketPresent\":false,"
           "\"runtimeExecutionPacketExecutable\":false,"
           "\"startsJavaService\":false,"
           "\"startsMiniKvService\":false,"
           "\"startsServices\":false,"
           "\"runtimeProbeAllowed\":false,"
           "\"liveReadAllowed\":false,"
           "\"activeShardPrototypeEnabled\":false,"
           "\"routerActivationAllowed\":false,"
           "\"writeRoutingAllowed\":false,"
           "\"writeCommandsAllowed\":false,"
           "\"adminCommandsAllowed\":false,"
           "\"loadRestoreCompactAllowed\":false,"
           "\"executionAllowed\":false,"
           "\"readOnly\":true}";
}

std::string format_read_only_boundary_fields_json() {
    return json_string_array(read_only_boundary_field_names());
}

} // namespace minikv::shard_readiness::boundary_fields
