#include "minikv/shard_readiness_route_catalog_evidence_chain.hpp"

namespace minikv::shard_readiness::route_catalog_evidence_chain {

std::string format_route_catalog_evidence_chain_json() {
    return "{\"catalogMode\":\"node-route-catalog-evidence-chain-read-only\","
           "\"sourceNodePlan\":\"docs/plans3/v471-post-route-catalog-expected-integrity-snapshot-roadmap.md\","
           "\"sourceFrozenReleaseVersion\":\"v188\","
           "\"sourceFrozenFixturePath\":\"fixtures/release/shard-readiness-v188.json\","
           "\"sourceFrozenDigest\":\"fnv1a64:565e5ce1fdb5f308\","
           "\"catalogedReleaseCount\":4,"
           "\"releaseRangeStart\":\"v185\","
           "\"releaseRangeEnd\":\"v188\","
           "\"latestCatalogedReleaseVersion\":\"v188\","
           "\"latestCatalogedDigest\":\"fnv1a64:565e5ce1fdb5f308\","
           "\"catalogedSections\":["
           "\"nodeRouteCatalogCloseoutSnapshot\","
           "\"nodeRouteCatalogAnchorRemovalAudit\","
           "\"nodeRouteCatalogExpectedIntegritySnapshotAudit\","
           "\"nodeRouteCatalogExpectedIntegritySnapshotFreeze\"],"
           "\"catalogEntries\":["
           "{\"releaseVersion\":\"v185\","
           "\"status\":\"node-route-catalog-closeout-snapshot-read-only\","
           "\"fixturePath\":\"fixtures/release/shard-readiness-v185.json\","
           "\"primarySection\":\"nodeRouteCatalogCloseoutSnapshot\","
           "\"evidenceDigest\":\"fnv1a64:6a6b4cbdac4bdb46\","
           "\"boundaryCatalogVersion\":\"read-only-boundary-fields.v12\","
           "\"fieldCount\":448,"
           "\"groupCount\":24,"
           "\"readOnly\":true,"
           "\"routerActivationAllowed\":false,"
           "\"writeRoutingAllowed\":false,"
           "\"executionAllowed\":false},"
           "{\"releaseVersion\":\"v186\","
           "\"status\":\"node-route-catalog-anchor-removal-audit-read-only\","
           "\"fixturePath\":\"fixtures/release/shard-readiness-v186.json\","
           "\"primarySection\":\"nodeRouteCatalogAnchorRemovalAudit\","
           "\"evidenceDigest\":\"fnv1a64:a5d69dff949088ee\","
           "\"boundaryCatalogVersion\":\"read-only-boundary-fields.v13\","
           "\"fieldCount\":472,"
           "\"groupCount\":25,"
           "\"readOnly\":true,"
           "\"routerActivationAllowed\":false,"
           "\"writeRoutingAllowed\":false,"
           "\"executionAllowed\":false},"
           "{\"releaseVersion\":\"v187\","
           "\"status\":\"node-route-catalog-expected-integrity-snapshot-audit-read-only\","
           "\"fixturePath\":\"fixtures/release/shard-readiness-v187.json\","
           "\"primarySection\":\"nodeRouteCatalogExpectedIntegritySnapshotAudit\","
           "\"evidenceDigest\":\"fnv1a64:f4459b7beacceedd\","
           "\"boundaryCatalogVersion\":\"read-only-boundary-fields.v15\","
           "\"fieldCount\":502,"
           "\"groupCount\":26,"
           "\"readOnly\":true,"
           "\"routerActivationAllowed\":false,"
           "\"writeRoutingAllowed\":false,"
           "\"executionAllowed\":false},"
           "{\"releaseVersion\":\"v188\","
           "\"status\":\"node-route-catalog-expected-integrity-snapshot-freeze-read-only\","
           "\"fixturePath\":\"fixtures/release/shard-readiness-v188.json\","
           "\"primarySection\":\"nodeRouteCatalogExpectedIntegritySnapshotFreeze\","
           "\"evidenceDigest\":\"fnv1a64:565e5ce1fdb5f308\","
           "\"boundaryCatalogVersion\":\"read-only-boundary-fields.v16\","
           "\"fieldCount\":525,"
           "\"groupCount\":27,"
           "\"readOnly\":true,"
           "\"routerActivationAllowed\":false,"
           "\"writeRoutingAllowed\":false,"
           "\"executionAllowed\":false}],"
           "\"versionedFixtureCatalogOnly\":true,"
           "\"rollingCurrentUsedForFrozenCatalog\":false,"
           "\"allCatalogedEntriesReadOnly\":true,"
           "\"allCatalogedFixturesVersioned\":true,"
           "\"allCatalogedDigestsPresent\":true,"
           "\"nodeConsumesFreshMiniKvEvidence\":false,"
           "\"miniKvRuntimeContractChanged\":false,"
           "\"nodeAddsEvidenceGate\":false,"
           "\"runtimeGateApprovalPresent\":false,"
           "\"runtimeExecutionPacketExecutable\":false,"
           "\"startsJavaService\":false,"
           "\"startsMiniKvService\":false,"
           "\"startsServices\":false,"
           "\"runtimeProbeAllowed\":false,"
           "\"liveReadAllowed\":false,"
           "\"activeShardPrototypeEnabled\":false,"
           "\"routerActivationAllowed\":false,"
           "\"writeRoutingAllowed\":false,"
           "\"writeCommandsAllowed\":false,"
           "\"adminCommandsAllowed\":false,"
           "\"loadRestoreCompactAllowed\":false,"
           "\"executionAllowed\":false,"
           "\"readOnly\":true}";
}

std::string format_route_catalog_evidence_chain_audit_json() {
    return "{\"auditMode\":\"node-route-catalog-evidence-chain-audit-read-only\","
           "\"sourceNodePlan\":\"docs/plans3/v472-post-route-catalog-cleanup-closeout-roadmap.md\","
           "\"sourceFrozenReleaseVersion\":\"v189\","
           "\"sourceFrozenFixturePath\":\"fixtures/release/shard-readiness-v189.json\","
           "\"sourceFrozenDigest\":\"fnv1a64:a595f2d9cdcbac8d\","
           "\"auditedChainSection\":\"nodeRouteCatalogEvidenceChain\","
           "\"nodeCleanupBatchStart\":\"Node v465\","
           "\"nodeCleanupBatchEnd\":\"Node v472\","
           "\"nodeCleanupCloseoutVersion\":\"Node v472\","
           "\"expectedCatalogedReleaseCount\":4,"
           "\"observedCatalogedReleaseCount\":4,"
           "\"releaseRangeStart\":\"v185\","
           "\"releaseRangeEnd\":\"v188\","
           "\"releaseRangeContiguous\":true,"
           "\"duplicateReleasesDetected\":false,"
           "\"allCatalogedDigestsPresent\":true,"
           "\"allCatalogedEntriesReadOnly\":true,"
           "\"allCatalogedFixturesVersioned\":true,"
           "\"latestDigestMatchesFrozenSource\":true,"
           "\"nodeCleanupCloseoutValidated\":true,"
           "\"nodeFullVitestShardsPassed\":true,"
           "\"nodeFullVitestFileCount\":394,"
           "\"nodeFullVitestTestCount\":1222,"
           "\"nodeTypecheckPassed\":true,"
           "\"nodeBuildPassed\":true,"
           "\"nodeConsumesFreshMiniKvEvidence\":false,"
           "\"miniKvRuntimeContractChanged\":false,"
           "\"auditOnly\":true,"
           "\"nodeAddsEvidenceGate\":false,"
           "\"runtimeGateApprovalPresent\":false,"
           "\"runtimeExecutionPacketExecutable\":false,"
           "\"startsJavaService\":false,"
           "\"startsMiniKvService\":false,"
           "\"startsServices\":false,"
           "\"runtimeProbeAllowed\":false,"
           "\"liveReadAllowed\":false,"
           "\"activeShardPrototypeEnabled\":false,"
           "\"routerActivationAllowed\":false,"
           "\"writeRoutingAllowed\":false,"
           "\"writeCommandsAllowed\":false,"
           "\"adminCommandsAllowed\":false,"
           "\"loadRestoreCompactAllowed\":false,"
           "\"executionAllowed\":false,"
           "\"readOnly\":true}";
}

} // namespace minikv::shard_readiness::route_catalog_evidence_chain
