#include "minikv/shard_readiness_route_catalog_closeout.hpp"

#include <string>

namespace minikv::shard_readiness::route_catalog_closeout {

std::string format_closeout_snapshot_json() {
    return "{\"snapshotMode\":\"node-route-catalog-final-closeout-snapshot-read-only\","
           "\"sourceNodePlan\":\"docs/plans3/v464-post-audit-route-catalog-final-closeout-roadmap.md\","
           "\"sourceFrozenReleaseVersion\":\"v184\","
           "\"sourceFrozenFixturePath\":\"fixtures/release/shard-readiness-v184.json\","
           "\"sourceFrozenDigest\":\"fnv1a64:5b7cd9ee9a9f2524\","
           "\"nodeFinalCloseoutVersion\":\"Node v464\","
           "\"routeCatalogBatchStart\":\"Node v433\","
           "\"routeCatalogBatchEnd\":\"Node v464\","
           "\"coveredNodeVersionCount\":32,"
           "\"focusedCloseoutTestFileCount\":7,"
           "\"focusedCloseoutTestCount\":17,"
           "\"nodeTypecheckPassed\":true,"
           "\"nodeBuildPassed\":true,"
           "\"nodeFullVitestFileCount\":393,"
           "\"nodeFullVitestTestCount\":1221,"
           "\"nodeConsumesFreshMiniKvEvidence\":false,"
           "\"miniKvRuntimeContractChanged\":false,"
           "\"snapshotOnly\":true,"
           "\"runtimeGateApprovalPresent\":false,"
           "\"runtimeExecutionPacketExecutable\":false,"
           "\"startsJavaService\":false,"
           "\"startsMiniKvService\":false,"
           "\"startsServices\":false,"
           "\"runtimeProbeAllowed\":false,"
           "\"liveReadAllowed\":false,"
           "\"activeShardPrototypeEnabled\":false,"
           "\"routerActivationAllowed\":false,"
           "\"writeRoutingAllowed\":false,"
           "\"writeCommandsAllowed\":false,"
           "\"adminCommandsAllowed\":false,"
           "\"loadRestoreCompactAllowed\":false,"
           "\"executionAllowed\":false,"
           "\"readOnly\":true}";
}

std::string format_anchor_removal_audit_json() {
    return "{\"auditMode\":\"node-route-catalog-anchor-removal-audit-read-only\","
           "\"sourceNodePlan\":\"docs/plans3/v467-post-route-catalog-anchor-removal-roadmap.md\","
           "\"sourceFrozenReleaseVersion\":\"v185\","
           "\"sourceFrozenFixturePath\":\"fixtures/release/shard-readiness-v185.json\","
           "\"sourceFrozenDigest\":\"fnv1a64:6a6b4cbdac4bdb46\","
           "\"auditedNodeVersion\":\"Node v467\","
           "\"sourceAnchorCompatibilityRemoved\":true,"
           "\"centralRouteTablePureFlatMapConsumer\":true,"
           "\"routeGroupTestsUseTypedCatalogIdentity\":true,"
           "\"routeOrderAlignmentRequired\":true,"
           "\"flatMapAlignmentRequired\":true,"
           "\"affectedRouteCatalogTestFileCount\":53,"
           "\"affectedRouteCatalogTestCount\":59,"
           "\"nodeTypecheckPassed\":true,"
           "\"nodeBuildPassed\":true,"
           "\"nodeConsumesFreshMiniKvEvidence\":false,"
           "\"miniKvRouteAnchorDependencyIntroduced\":false,"
           "\"miniKvRuntimeContractChanged\":false,"
           "\"auditOnly\":true,"
           "\"nodeAddsEvidenceGate\":false,"
           "\"runtimeGateApprovalPresent\":false,"
           "\"runtimeExecutionPacketExecutable\":false,"
           "\"startsJavaService\":false,"
           "\"startsMiniKvService\":false,"
           "\"startsServices\":false,"
           "\"runtimeProbeAllowed\":false,"
           "\"liveReadAllowed\":false,"
           "\"activeShardPrototypeEnabled\":false,"
           "\"routerActivationAllowed\":false,"
           "\"writeRoutingAllowed\":false,"
           "\"writeCommandsAllowed\":false,"
           "\"adminCommandsAllowed\":false,"
           "\"loadRestoreCompactAllowed\":false,"
           "\"executionAllowed\":false,"
           "\"readOnly\":true}";
}

std::string format_expected_integrity_snapshot_audit_json() {
    return "{\"auditMode\":\"node-route-catalog-expected-integrity-snapshot-audit-read-only\","
           "\"sourceNodePlan\":\"docs/plans3/v471-post-route-catalog-expected-integrity-snapshot-roadmap.md\","
           "\"sourceFrozenReleaseVersion\":\"v186\","
           "\"sourceFrozenFixturePath\":\"fixtures/release/shard-readiness-v186.json\","
           "\"sourceFrozenDigest\":\"fnv1a64:a5d69dff949088ee\","
           "\"auditedNodeVersion\":\"Node v471\","
           "\"anchorFieldsRemovedByNodeV468\":true,"
           "\"summaryBuilderIntroducedByNodeV469\":true,"
           "\"expectedSummaryCentralizedByNodeV470\":true,"
           "\"expectedIntegritySnapshotFactoryMovedByNodeV471\":true,"
           "\"routeQualityDefaultSnapshotReusesExpectedSummary\":true,"
           "\"routeQualityServiceConsumesCatalogIntegrityFactory\":true,"
           "\"serviceLocalIntegrityFallbackRemoved\":true,"
           "\"catalogEvaluatorParityTested\":true,"
           "\"duplicateDomainCountLiteralsRemoved\":true,"
           "\"miniKvComputesNodeRouteSummary\":false,"
           "\"miniKvOwnsNodeRouteQualitySnapshot\":false,"
           "\"miniKvOwnsNodeCatalogIntegritySnapshot\":false,"
           "\"focusedExpectedSummaryTestFileCount\":3,"
           "\"focusedExpectedSummaryTestCount\":7,"
           "\"focusedExpectedIntegritySnapshotTestFileCount\":3,"
           "\"focusedExpectedIntegritySnapshotTestCount\":7,"
           "\"nodeTypecheckPassed\":true,"
           "\"nodeBuildPassed\":true,"
           "\"nodeConsumesFreshMiniKvEvidence\":false,"
           "\"miniKvRuntimeContractChanged\":false,"
           "\"auditOnly\":true,"
           "\"nodeAddsEvidenceGate\":false,"
           "\"runtimeGateApprovalPresent\":false,"
           "\"runtimeExecutionPacketExecutable\":false,"
           "\"startsJavaService\":false,"
           "\"startsMiniKvService\":false,"
           "\"startsServices\":false,"
           "\"runtimeProbeAllowed\":false,"
           "\"liveReadAllowed\":false,"
           "\"activeShardPrototypeEnabled\":false,"
           "\"routerActivationAllowed\":false,"
           "\"writeRoutingAllowed\":false,"
           "\"writeCommandsAllowed\":false,"
           "\"adminCommandsAllowed\":false,"
           "\"loadRestoreCompactAllowed\":false,"
           "\"executionAllowed\":false,"
           "\"readOnly\":true}";
}

std::string format_expected_integrity_snapshot_freeze_json() {
    return "{\"freezeMode\":\"node-route-catalog-expected-integrity-snapshot-freeze-read-only\","
           "\"sourceNodePlan\":\"docs/plans3/v471-post-route-catalog-expected-integrity-snapshot-roadmap.md\","
           "\"frozenReleaseVersion\":\"v187\","
           "\"frozenFixturePath\":\"fixtures/release/shard-readiness-v187.json\","
           "\"frozenEvidenceDigest\":\"fnv1a64:f4459b7beacceedd\","
           "\"frozenStatus\":\"node-route-catalog-expected-integrity-snapshot-audit-read-only\","
           "\"frozenWindowEndNodeVersion\":\"Node v471\","
           "\"frozenSplitRouteGroupCount\":39,"
           "\"frozenBoundaryCatalogVersion\":\"read-only-boundary-fields.v15\","
           "\"frozenBoundaryFieldCount\":502,"
           "\"rollingCurrentUsedForFrozenBaseline\":false,"
           "\"preservesExpectedIntegritySnapshotAudit\":true,"
           "\"preservesNodeV471CatalogOwnershipCleanup\":true,"
           "\"preservesRouteCatalogWindow\":true,"
           "\"preservesBoundaryCatalog\":true,"
           "\"miniKvOwnsNodeCatalogIntegritySnapshot\":false,"
           "\"nodeConsumesFreshMiniKvEvidence\":false,"
           "\"miniKvRuntimeContractChanged\":false,"
           "\"nodeAddsEvidenceGate\":false,"
           "\"runtimeGateApprovalPresent\":false,"
           "\"runtimeExecutionPacketExecutable\":false,"
           "\"startsJavaService\":false,"
           "\"startsMiniKvService\":false,"
           "\"startsServices\":false,"
           "\"runtimeProbeAllowed\":false,"
           "\"liveReadAllowed\":false,"
           "\"activeShardPrototypeEnabled\":false,"
           "\"routerActivationAllowed\":false,"
           "\"writeRoutingAllowed\":false,"
           "\"writeCommandsAllowed\":false,"
           "\"adminCommandsAllowed\":false,"
           "\"loadRestoreCompactAllowed\":false,"
           "\"executionAllowed\":false,"
           "\"readOnly\":true}";
}

} // namespace minikv::shard_readiness::route_catalog_closeout
